# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1460576441dccb3fdfc8b1b4f439ef8876a888e61fb90a4344ea58a4548ee1d9351050a1048bba55eb92f61b789143ce2757c6f0c8601a51d1a7503a57baaa19

test:
  secret_key_base: eab57a4ffffeae2346e41d93d4036c6010046b60c598f4e1e721dfa3e26eb2599c683789ce90675aee640da9f68e260bfe2fd4a0987f0e6a4fd4b7593eec0e65

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
